
import robotics from "../assets/robotics_640.webp"
import invoiceimg from "../assets/d587e3aac575273419c9e2c8f15dbc5a.webp"

export const invoices = [
    {
        name: "Santa Monica",
        number: 1995,
        amount: "$10,800",
        due: "12/05/1995",
    },
    {
        name: "Stankonia",
        number: 2000,
        amount: "$8,000",
        due: "10/31/2000",
    },
    {
        name: "Ocean Avenue",
        number: 2003,
        amount: "$9,500",
        due: "07/22/2003",
    },
    {
        name: "Tubthumper",
        number: 1997,
        amount: "$14,000",
        due: "09/01/1997",
    },
    {
        name: "Wide Open Spaces",
        number: 1998,
        amount: "$4,600",
        due: "01/27/1998",
    },
]

export const materialList = [
    {id: 1, name: "Pocket Tissues", cost: [{value:50, type: "¥"},{value:0, type: "-"}],location: ["Poppo", "Pharmacies", "Encounters"] },
    {id: 2, name: "Paper Plate", cost: [{value:0, type: "-"}],location: ["Encounters"] },
    {id: 3, name: "Iron Plate", cost: [{value:100, type: "SP"},{value:0, type: "-"}],location: ["Encounters", "Onodera's Wares"] },
    {id: 4, name: "Bronze Plate", cost: [{value:0, type: "-"},{value:10, type: "Tags"},{value:10, type: "Chips"},{value:1000, type: "SP"},{value:1000, type: "Shogi"}],location: ["Encounters", "Gambling Hall", "Casino", "Onodera's Wares", "Shogi"] },
    {id: 5, name: "Silver Plate", cost: [{value:100, type: "Tags"},{value:100, type: "Chips"},{value:10000, type: "SP"},{value:10000, type: "Shogi"}],location: ["Gambling Hall", "Casino", "Onodera's Wares", "Shogi"] },
    {id: 6, name: "Gold Plate", cost: [{value:1000, type: "Tags"},{value:1000, type: "Chips"},{value:100000, type: "SP"},{value:100000, type: "Shogi"}],location: ["Lost Item Reward", "Gambling Hall", "Casino", "Onodera's Wares", "Shogi"] },
    {id: 7, name: "Platinum Plate", cost: [{value:2000, type: "Tags"},{value:2000, type: "Chips"},{value:200000, type: "SP"},{value:200000, type: "Shogi"}],location: ["Gambling Hall", "Casino", "Onodera's Wares", "Shogi"] },
    {id: 8, name: "Homestyle Chicken Cat Food", cost: [{value:300, type: "¥"}],location: ["Poppo (Showa, E. Shichifuku)", "Deco Rush", "Welcome Pharmacy", "Extract Shop (Seiryo)"] },
    {id: 9, name: "Miso Crispy Beef Cat Food", cost: [{value:300, type: "¥"}],location: ["Poppo (Tenkaichi, W. Shichifuku)", "Deco Rush", "Welcome Pharmacy", "Extract Shop (Seiryo)"] },
    {id: 10, name: "Fresh Tuna Cat Food", cost: [{value:300, type: "¥"}],location: ["Poppo (E. Shichifuku, Jinnai Ext., Tsurukame)", "Deco Rush", "Welcome Pharmacy", "Extract Shop (Seiryo)"] },
    {id: 11, name: "Cheese Salmon Paté Cat Food", cost: [{value:300, type: "¥"}],location: ["Poppo (Tenkaichi, Jinnai Ext., Tsurukame)", "Deco Rush", "Welcome Pharmacy", "Extract Shop (Seiryo)"] },
    {id: 12, name: "White Fish and Sardine Cat Food", cost: [{value:300, type: "¥"}],location: ["Poppo (Showa)", "Deco Rush", "Extract Shop (Seiryo)"] },
    {id: 13, name: "Bonito Flake Cat Food", cost: [{value:300, type: "¥"}],location: ["Poppo (W. Shichifuku)", "Deco Rush", "Extract Shop (Seiryo)"] },
    {id: 14, name: "Gold Tuna Cat Food", cost: [{value:600, type: "SP"}],location: ["Onodera's Wares", "Heaven's Golf"] },
    {id: 15, name: "Dog Food", cost: [{value:500, type: "¥"}],location: ["Deco Rush"] },
    {id: 16, name: "Small Screw", cost: [{value:200, type: "¥"}],location: ["Extract Shop (Any)"] },
    {id: 17, name: "Exquisite Screw", cost: [{value:600, type: "¥"}],location: ["General Goods Cart", "Extract Shop (Seiryo)"] },
    {id: 18, name: "Top Shelf Screw", cost: [{value:1000, type: "¥"}],location: ["Benten Pawn"] },
    {id: 19, name: "Cheap Plastic", cost: [{value:300, type: "¥"}],location: ["General Goods Cart"] },
    {id: 20, name: "Sturdy Plastic", cost: [{value:800, type: "¥"}],location: ["General Goods Cart"] },
    {id: 21, name: "High-grade Plastic", cost: [{value:2300, type: "¥"}],location: ["Ebisu Pawn Yokohama"] },
    {id: 22, name: "Shabby Wire", cost: [{value:700, type: "¥"}],location: ["Coming Boon", "General Goods Cart", "Extract Shop (Seiryo)"] },
    {id: 23, name: "Quality Wire", cost: [{value:2100, type: "¥"}],location: ["Coming Boon", "General Goods Cart", "Extract Shop (Seiryo)"] },
    {id: 24, name: "High-end Wire", cost: [{value:5500, type: "¥"}],location: ["General Goods Cart"] },
    {id: 25, name: "Dull Aluminum", cost: [{value:700, type: "¥"}],location: ["General Goods Cart"] },
    {id: 26, name: "Gleaming Aluminum", cost: [{value:5900, type: "¥"}],location: ["General Goods Cart"] },
    {id: 27, name: "Dented Carbon", cost: [{value:500, type: "¥"}],location: ["General Goods Cart", "Extract Shop (Seiryo)"] },
    {id: 28, name: "Flexible Carbon", cost: [{value:4700, type: "¥"}],location: ["General Goods Cart"] },
    {id: 29, name: "Rusted Electrical Wire", cost: [{value:1800, type: "¥"}],location: ["Extract Shop (Any)"] },
    {id: 30, name: "Clean Electrical Wire", cost: [{value:9400, type: "¥"}],location: ["General Goods Cart"] },
    {id: 31, name: "Dirty Iron", cost: [{value:2400, type: "¥"}],location: ["General Goods Cart", "Extract Shop (Seiryo)"] },
    {id: 32, name: "Sturdy Iron", cost: [{value:7800, type: "¥"}],location: ["General Goods Cart", "Extract Shop (Any)"] },
    {id: 33, name: "Old Circuit", cost: [{value:2400, type: "¥"}],location: ["Benten Pawn (limited)", "Extract Shop (Any)"] },
    {id: 34, name: "Precise Circuit", cost: [{value:7200, type: "¥"}],location: ["General Goods Cart"] },
    {id: 35, name: "Worn Magnet", cost: [{value:1700, type: "¥"}],location: ["Extract Shop (Any)"] },
    {id: 36, name: "Strong Magnet", cost: [{value:6300, type: "¥"}],location: ["General Goods Cart"] },
    {id: 37, name: "Stretched Coil", cost: [{value:1700, type: "¥"}],location: ["General Goods Cart", "Extract Shop (Any)"] },
    {id: 38, name: "Sturdy Coil", cost: [{value:6300, type: "¥"}],location: ["General Goods Cart"] },
    {id: 39, name: "Abundant Oil", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 40, name: "Clear Resin", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 41, name: "Solid Paint (White)", cost: [{value:5400, type: "¥"}],location: ["Deco Rush"] },
    {id: 42, name: "Solid Paint (Black)", cost: [{value:5400, type: "¥"}],location: ["Deco Rush"] },
    {id: 43, name: "Solid Paint (Blue)", cost: [{value:5400, type: "¥"}],location: ["Deco Rush"] },
    {id: 44, name: "Solid Paint (Red)", cost: [{value:5400, type: "¥"}],location: ["Deco Rush"] },
    {id: 45, name: "Striped Paint", cost: [{value:6900, type: "¥"}],location: ["Deco Rush"] },
    {id: 46, name: "Checkered Paint", cost: [{value:6900, type: "¥"}],location: ["Deco Rush"] },
    {id: 47, name: "Cute Paint", cost: [{value:6900, type: "¥"}],location: ["Deco Rush"] },
    {id: 48, name: "Floral Paint", cost: [{value:6900, type: "¥"}],location: ["Deco Rush"] },
    {id: 49, name: "Colorful Paint", cost: [{value:6900, type: "¥"}],location: ["Deco Rush"] },
    {id: 50, name: "Elegant Paint", cost: [{value:6900, type: "¥"}],location: ["Deco Rush"] },
    {id: 51, name: "Natural Paint", cost: [{value:1000, type: "SP"}],location: ["Onodera's Wares"] },
    {id: 52, name: "Camo Paint (Green)", cost: [{value:6900, type: "¥"}],location: ["Coming Boon"] },
    {id: 53, name: "Camo Paint (Brown)", cost: [{value:6900, type: "¥"}],location: ["Coming Boon"] },
    {id: 54, name: "Camo Paint (Blue)", cost: [{value:6900, type: "¥"}],location: ["Coming Boon"] },
    {id: 55, name: "Anime Paint", cost: [{value:1000, type: "SP"}],location: ["Onodera's Wares"] },
    {id: 56, name: "Dragon Paint", cost: [{value:1000, type: "SP"}],location: ["Onodera's Wares"] },
    {id: 57, name: "Refined Iron", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 58, name: "Impure Lead", cost: [{value:100, type: "¥"}],location: ["Extract Shop (Any)"] },
    {id: 59, name: "High-purity Lead", cost: [{value:4500, type: "¥"}],location: ["General Goods Cart", "Extract Shop (Seiryo)"] },
    {id: 60, name: "Tempered Steel", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 61, name: "Cloudy Pane", cost: [{value:380, type: "¥"}],location: ["Extract Shop (Any)"] },
    {id: 62, name: "Clear Pane", cost: [{value:2800, type: "¥"}],location: ["General Goods Cart", "Extract Shop (Seiryo)"] },
    {id: 63, name: "Immaculate Pane", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 64, name: "Worn-out Rubber", cost: [{value:100, type: "¥"}],location: ["Extract Shop (Any)"] },
    {id: 65, name: "Passable Rubber", cost: [{value:2550, type: "¥"}],location: ["General Goods Cart", "Extract Shop (Seiryo)"] },
    {id: 66, name: "Super-durable Rubber", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 67, name: "Mobile Basic Report", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 68, name: "Mobile Application Report", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 69, name: "Mobile Combination Report", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 70, name: "Assault Basic Report", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 71, name: "Assault Application Report", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 72, name: "Assault Combination Report", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 73, name: "Fortress Basic Report", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 74, name: "Fortress Application Report", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 75, name: "Fortress Combination Report", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 76, name: "M-Weapon Basic Report", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 77, name: "M-Weapon Application Report", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 78, name: "M-Weapon Combination Report", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 79, name: "R-Weapon Basic Report", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 80, name: "R-Weapon Application Report", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 81, name: "R-Weapon Combination Report", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 82, name: "IP1 Data", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 83, name: "IP2 Data", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 84, name: "IP3 Data", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 85, name: "AI1 Data", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 86, name: "AI2 Data", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 87, name: "AI3 Data", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 88, name: "CF1 Data", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 89, name: "CF2 Data", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 90, name: "CF3 Data", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 91, name: "SP1 Data", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 92, name: "SP2 Data", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 93, name: "SP3 Data", cost: [{value:0, type: "-"}],location: ["Robotics Club Matches"] },
    {id: 94, name: "Pebble", cost: [{value:100, type: "¥"}],location: ["Extract Shop (Any)"] },
    {id: 95, name: "Twig", cost: [{value:100, type: "¥"}],location: ["Extract Shop (Any)"] },
    {id: 96, name: "Earthworm", cost: [{value:300, type: "¥"}],location: ["Extract Shop (Any)"] },
    {id: 97, name: "Mugwort", cost: [{value:5000, type: "¥"}],location: ["Flowers 2 Go"] },
    {id: 98, name: "Four Leaf Clover", cost: [{value:5000, type: "¥"}],location: ["Flowers 2 Go"] },
    {id: 99, name: "Pachinko Ball", cost: [{value:3000, type: "¥"}],location: ["Benten Pawn (limited)", "Extract Shop (Any)"] },
    {id: 100, name: "Prize Medal", cost: [{value:3000, type: "¥"}],location: ["The Bee (Darts Shop)", "Extract Shop (Any)"] },
    {id: 101, name: "Empty Bottle", cost: [{value:100, type: "¥"}],location: ["Extract Shop (Any)"] },
    {id: 102, name: "Stretchy Rubber", cost: [{value:500, type: "¥"}],location: ["Kinka Pharmacy", "Extract Shop (Seiryo)"] },
    {id: 103, name: "Cigarette Butt", cost: [{value:300, type: "¥"}],location: ["Extract Shop (Seiryo)"] },
    {id: 104, name: "Bullet", cost: [{value:0, type: "-"}],location: ["Rare Cat Reward"] },
    {id: 105, name: "Dirty Cloth", cost: [{value:0, type: "-"}],location: ["Common Cat Reward"] },
    {id: 106, name: "Sacred Rot", cost: [{value:12000, type: "¥"}],location: ["Extract Shop (Any)"] },
    {id: 107, name: "Sacred Wood", cost: [{value:25000, type: "¥"}],location: ["Yi Xing Tang", "Extract Shop (Seiryo)"] },
    {id: 108, name: "Sacred Tree", cost: [{value:50000, type: "¥"}],location: ["Yi Xing Tang"] },
    {id: 109, name: "Mysterious Stone", cost: [{value:12000, type: "¥"}],location: ["Extract Shop (Any)"] },
    {id: 110, name: "Beautiful Seashell", cost: [{value:10000, type: "¥"}],location: ["Yi Xing Tang", "Extract Shop (Seiryo)"] },
    {id: 111, name: "Eye of the Dragon", cost: [{value:58000, type: "¥"}],location: ["Le Marche (limited)", "La chatte blanche (limited)"] },
    {id: 112, name: "Red Pyroxene", cost: [{value:83000, type: "¥"}],location: ["Drone Racing: Single Race (Track 10)", "Le Marche (limited)", "La chatte blanche (limited)", "Deco Rush"] },
    {id: 113, name: "Blue Pyroxene", cost: [{value:83000, type: "¥"}],location: ["Drone Racing: Single Race (Track 9)", "Le Marche (limited)", "La chatte blanche (limited)", "Deco Rush"] },
    {id: 114, name: "Yellow Pyroxene", cost: [{value:83000, type: "¥"}],location: ["Drone Racing: Single Race (Track 8)", "Le Marche (limited)", "La chatte blanche (limited)", "Deco Rush"] },
    {id: 115, name: "Rainbow Pyroxene", cost: [{value:100000, type: "¥"}],location: ["Le Marche (limited)", "La chatte blanche (limited)", "Benten Pawn (limited)"] },
    {id: 116, name: "Beehive", cost: [{value:1300, type: "¥"}],location: ["Yi Xing Tang", "Extract Shop (Seiryo)"] },
    {id: 117, name: "Scorpion", cost: [{value:5600, type: "¥"}],location: ["Yi Xing Tang", "Extract Shop (Seiryo)"] },
    {id: 118, name: "Mysterious Leaf", cost: [{value:10000, type: "¥"}],location: ["Yi Xing Tang"] },
    {id: 119, name: "Mysterious Fruit", cost: [{value:10000, type: "¥"}],location: ["Yi Xing Tang"] },
    {id: 120, name: "Empty Extract Vessel", cost: [{value:100000, type: "¥"},{value:4800, type: "SP"},{value:50000, type: "Chips"}],location: ["Yi Xing Tang (limited)", "Onodera's Wares (limited)", "Heaven's Door Casino"] },
    {id: 121, name: "Pansy", cost: [{value:350, type: "¥"}],location: ["Flowers 2 Go"] },
    {id: 122, name: "Rose", cost: [{value:1280, type: "¥"}],location: ["Flowers 2 Go"] },
    {id: 123, name: "Lily", cost: [{value:2650, type: "¥"}],location: ["Flowers 2 Go"] },
    {id: 124, name: "Daikon", cost: [{value:158, type: "¥"}],location: ["Hero's Harvest"] },
    {id: 125, name: "Tomato", cost: [{value:94, type: "¥"}],location: ["Hero's Harvest"] },
    {id: 126, name: "Hot Pepper", cost: [{value:0, type: "-"}],location: ["Found on the ground"] },
    {id: 127, name: "Potato", cost: [{value:322, type: "¥"}],location: ["Hero's Harvest"] },
    {id: 128, name: "Onion", cost: [{value:72, type: "¥"}],location: ["Hero's Harvest"] },
    {id: 129, name: "Garlic", cost: [{value:598, type: "¥"}],location: ["Hero's Harvest"] },
    {id: 130, name: "Mysterious Bulb", cost: [{value:9800, type: "¥"}],location: ["Hero's Harvest", "Extract Shop (Seiryo)"] },
    {id: 131, name: "Mysterious Mushroom", cost: [{value:12800, type: "¥"}],location: ["Hero's Harvest"] },
    {id: 132, name: "Mysterious Seeds", cost: [{value:13500, type: "¥"}],location: ["Hero's Harvest"] },
    {id: 133, name: "Master Frame Blueprints", cost: [{value:100000, type: "¥"}],location: ["General Goods Cart", "Benten Pawn (limited)"] },
    {id: 134, name: "Master Propeller Blueprints", cost: [{value:200000, type: "¥"}],location: ["General Goods Cart"] },
    {id: 135, name: "Master Motor Blueprints", cost: [{value:30000, type: "Chips"}],location: ["Heaven's Door Casino"] },
    {id: 136, name: "Master Turbo Blueprints", cost: [{value:200000, type: "¥"}],location: ["Ebisu Pawn Kamurocho"] },
    {id: 137, name: "Master ESC Blueprints", cost: [{value:1000, type: "SP"}],location: ["Onodera's Wares"] }
]

export interface MaterialCheckList {
    id: number,
    qty: number,
    name: string,
    cost: any[],
    location: any[],
    check: boolean
}


export const routesList = [
    { id: "home", title: "Home", route: "/home" },
    { id: "material", title: "Material", route: "/material" },    
    { id: "invoices", title: "Invoices", route: "/invoices" },
    // { id: "expenses", title: "Expenses", route: "/expenses" },   
]

export const menuList = [    
    { id: "material", title: "Material",description:"List of Materials with location, price and checklist", route: "/material", img: robotics },        
    // { id: "invoices", title: "Invoices", route: "/invoices" },
    // { id: "expenses", title: "Expenses", route: "/expenses" },   
]